version: '3.9'

services:
  database:
    image: mariadb:10.6
    container_name: acelera_database
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=acelera
      - MYSQL_USER=acelera
      - MYSQL_PASSWORD=acelera
      - MYSQL_DATABASE=acelera

  app:
    image: ambientum/php:7.3-nginx
    container_name: acelera_app
    ports:
      - "8080:8080"
    environment:
      - XDEBUG_ENABLED=true
      - XDEBUG_MODE=debug
    volumes:
      - .:/var/www/app
    links:
      - database
